/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Employee {
  id: Generated<string>;
  name: string;
  tenant_id: string;
}

export interface Tenant {
  connection_string: string | null;
  created_at: Generated<Timestamp>;
  has_instance: Generated<boolean | null>;
  id: Generated<string>;
  name: string;
}

export interface DB {
  employee: Employee;
  tenant: Tenant;
}
